### ISSUE TITLE
Replace ${{ PYTHON }} variable in script?

### ISSUE THREAD

**Issue by beenje** [conda-incubator/conda-recipe-manager#110]
For python recipes in conda-forge, the script is usually: `script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation`

When converting a recipe with `conda-recipe-manager`,  this is translated to `script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation`.
If I try to build such a recipe with `rattler-build`, it fails because `PYTHON` is replaced with an empty string in `conda_build.sh`.
Not sure if this is a `rattler-build` issue or if it's on purpose. In the documentation, I can see they always use `script: python -m pip...`.

Should `conda-recipe-manager` directly convert `script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation` to `script: python -m pip install . -vv --no-deps --no-build-isolation` ?

**Comment by schuylermartin45** [comment]
This is an issue with `rattler-build`: https://github.com/prefix-dev/rattler-build/issues/851

The Conda Recipe Manager's conversion tooling should be replacing the syntax for JINJA variables, which is exactly what is happening here. It is not up to the conversion script to arbitrarily decide what the variable "should be". That is up to the build system.

**Comment by schuylermartin45** [comment]
The issue I tagged above may not actually be a perfect match. I'm going to sync with Wolf offline to see if he has a better issue open or if we need to create a new one.

**Comment by wolfv** [comment]
Yes, it should be fixed in `rattler-build`.
