### ISSUE TITLE
Develop a Code of Conduct/Rules of Engagement

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#145]
As the project has started to gain some traction from the Conda community, we need to adapt a Code of Conduct.

**Comment by jezdez** [comment]
Please read the [conda governance policy](https://github.com/conda/governance), the Conda Code of Conduct exists and is implied as a conda project, no need to adapt a Code of Conduct.

**Comment by schuylermartin45** [comment]
Should it be copied or linked to in this repo? How do we integrate with GitHub's expectation that a Code of Conduct file exists in the repo?

**Comment by jezdez** [comment]
We have a repo with predefined files and workflows available for conda project, to take care of this (and also issue templates, ref #158) that will also copy the code of conduct (and update it when a change happens) for the repos that have been initialized.

The init workflow can be seen here: https://github.com/conda/infrastructure/blob/c24a6b6e68f1a4cc50e4cee8d625cf6ffd9861cb/.github/workflows/init.yml
The update workflow: https://github.com/conda/infrastructure/blob/c24a6b6e68f1a4cc50e4cee8d625cf6ffd9861cb/.github/workflows/update.yml

**Comment by jezdez** [comment]
Just kicked off the init workflow in https://github.com/conda/infrastructure/actions/runs/11061066717

**Comment by kenodegard** [comment]
need to give the bot access to this repo first

**Comment by schuylermartin45** [comment]
Let me do that real quick. TIL, didn't know about any of this.

**Comment by schuylermartin45** [comment]
Done, hopefully `write` is sufficient for the bot.

**Comment by schuylermartin45** [comment]
Glad I wrote this ticket, because clearly the conda-bot wasn't configured. But I'm a complete dummy for not checking that we actually do have a COC file from the initial repo commit. It's been a busy week...

**Comment by schuylermartin45** [comment]
Marking this as closed as we are now onboarded with conda-bot.
![robots.txt](https://jhall.io/images/robot-overlords.jpg)
