### ISSUE TITLE
Release: v0.3.0

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#155]
The last release of CRM was in July. We should bump the minor as the project now includes a lot of newer modules that greatly expand the scope of the library.

There have also been a handful of user issues resolved recently.

**Comment by jezdez** [comment]
I'd suggest making that version the cut-off to propose graduation to the main conda organization, given the increasing scope of the project and the impending use to convert recipes with it in Anaconda and conda-forge. That would clarify to the conda community that this has reached a level of maturity to rely on, basically, and is not in incubation anymore.

**Comment by schuylermartin45** [comment]
To clarify, are you thinking the next release should be called v1.0.0?

**Comment by schuylermartin45** [comment]
I've had a few requests from package builders to cut a new release. I might need to make an interim release in the short-term.

**Comment by schuylermartin45** [comment]
#194 includes a minor fix that marks the true v0.3.0 release point.

**Comment by schuylermartin45** [comment]
Feedstock PR: https://github.com/conda-forge/conda-recipe-manager-feedstock/pull/2

**Comment by schuylermartin45** [comment]
New version is available on conda-forge. Closing.
