### ISSUE TITLE
over quoting jinja2 items

### ISSUE THREAD

**Issue by beckermr** [conda-incubator/conda-recipe-manager#197]
**What happened?**

It appears that CRM is overquoting some jinja2 items. See this bug report comment on smithy for the error and steps to reproduce: https://github.com/conda-forge/conda-smithy/issues/2085#issuecomment-2407734898

**To Reproduce**

**Additional Details (please complete the following information):**
 - OS: [e.g. MacOS M1, Windows]
 - Conda Recipe Manager version [e.g. `0.2.0`]
 - Any other context about the problem that was found.

**Comment by schuylermartin45** [comment]
Tagging #189 as it seems relevant. Though my gut says this is likely an issue with `parser._utils.py::quote_special_strings()` we can address.
