### ISSUE TITLE
Address drop in rattler-build compatibility

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/conda-recipe-manager#74]
`rattler-build@0.17.0` Added a new error check that dropped our recipe compatibility enough to start failing some of our integration tests.

In the `conda-forge` dataset, we now get:
```
    "Error:   \u00d7 Parsing: failed to render Jinja expression: undefined value: No compiler": 11,
```

Figuring out this issue and finding a solution will fix our failing integration test(s).

**Comment by schuylermartin45** [comment]
If we install `go` and `go-nocgo` to the test environment, this would solve the issue. Similarly we could remove a ton of missing environment errors if I stuffed the test environment with a bunch of blank environment variables.

I've talked to Wolf previously about a similar issue and I'm hoping we could add a secondary dry-run mode that acts more like a linter for recipe files.

**Comment by schuylermartin45** [comment]
> Similarly we could remove a ton of missing environment errors if I stuffed the test environment with a bunch of blank environment variables.

Adding `PREFIX` and `RECIPE_DIR` alone would potentially fix hundreds of integration testing errors.

**Comment by jezdez** [comment]
> > Similarly we could remove a ton of missing environment errors if I stuffed the test environment with a bunch of blank environment variables.
> 
> Adding `PREFIX` and `RECIPE_DIR` alone would potentially fix hundreds of integration testing errors.

Yeah, that sounds like an issue with the test harness, and if rattler-build is starting to be more picky about it, it's worth updating it

**Comment by schuylermartin45** [comment]
I am currently addressing it in the test environment but I do not agree that that is the permanent way to solve this.

Our ability to convert recipes successfully should not be determined by whether or not I have `go` installed. Ideally the tooling should allow us to analyze recipes without being dependent on a local environment.

**Comment by jezdez** [comment]
> I am currently addressing it in the test environment but I do not agree that that is the permanent way to solve this.
> 
> Our ability to convert recipes successfully should not be determined by whether or not I have `go` installed. Ideally the tooling should allow us to analyze recipes without being dependent on a local environment.

Fair, agreed

**Comment by schuylermartin45** [comment]
I filed a PR with `rattler-build`: https://github.com/prefix-dev/rattler-build/pull/928
There needs to be a change on their end for `go` recipes to dry-run build successfully.
