### ISSUE TITLE
Output schema reference by default

### ISSUE THREAD

**Issue by dhirschfeld** [conda-incubator/conda-recipe-manager#79]
It might be nice to output the schema reference so that you get nice completions by default:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
```

**Comment by dhirschfeld** [comment]
Also, awesome tool! I think this will be super useful. First time giving it a go and it seems to work great! :heart:

**Comment by schuylermartin45** [comment]
Apologies for not responding to this sooner. I need to figure out why I'm not getting notified on new issues to this repo.

I'm not sure if I completely understand this request. Are you talking about completions for YAML for an IDE? I'm not sure what else you could be referring too.

**Comment by Hofer-Julian** [comment]
> Apologies for not responding to this sooner. I need to figure out why I'm not getting notified on new issues to this repo.
> 
> I'm not sure if I completely understand this request. Are you talking about completions for YAML for an IDE? I'm not sure what else you could be referring too.

Not the author of the issue but I think this feature isn't necessary anymore. The schema is nowadays on the schema store and every file called "recipe.yaml" will get completions and error messages in IDEs

**Comment by dhirschfeld** [comment]
> > Apologies for not responding to this sooner. I need to figure out why I'm not getting notified on new issues to this repo.
> > I'm not sure if I completely understand this request. Are you talking about completions for YAML for an IDE? I'm not sure what else you could be referring too.
> 
> Not the author of the issue but I think this feature isn't necessary anymore. The schema is nowadays on the schema store and every file called "recipe.yaml" will get completions and error messages in IDEs

True - completions do work by default now so this isn't needed anymore.
